# Generated by Django 5.1.7 on 2025-03-15 12:56

import django.db.models.deletion
from django.db import migrations, models

import activitypub.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=activitypub.utils.generate_ulid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("webfinger", models.CharField(max_length=1024, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("summary", models.TextField(blank=True, null=True)),
                ("inbox_url", models.URLField(blank=True, null=True)),
                ("outbox_url", models.URLField(blank=True, null=True)),
                ("followers_url", models.URLField(blank=True, null=True)),
                ("following_url", models.URLField(blank=True, null=True)),
                ("actor_url", models.URLField(blank=True, null=True)),
                ("profile_url", models.URLField(blank=True, null=True)),
                ("shared_inbox_url", models.URLField(blank=True, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                ("public_key", models.TextField(blank=True, null=True)),
                ("private_key", models.TextField(blank=True, null=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icons")),
                (
                    "header",
                    models.ImageField(blank=True, null=True, upload_to="headers"),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.URLField(max_length=1024, primary_key=True, serialize=False),
                ),
                ("activity_type", models.CharField(max_length=50)),
                ("object_uri", models.CharField(blank=True, null=True)),
                ("object_json", models.JSONField(blank=True, null=True)),
                ("additional_fields", models.JSONField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, null=True)),
                ("raw_activity", models.JSONField(blank=True, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="activitypub.actor",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_activities",
                        to="activitypub.actor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followed_on", models.DateTimeField(auto_now_add=True)),
                ("accepted", models.BooleanField(default=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="activitypub.actor",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="activitypub.actor",
                    ),
                ),
            ],
            options={
                "unique_together": {("actor", "target")},
            },
        ),
    ]
