WORKOUT_STATUS_PENDING = "pending"
WORKOUT_STATUS_PROCESSING = "processing"
WORKOUT_STATUS_FINISHED = "finished"
WORKOUT_STATUS_ERROR = "error"

WORKOUT_STATUSES_LIST = [
    WORKOUT_STATUS_PENDING,
    WORKOUT_STATUS_PROCESSING,
    WORKOUT_STATUS_FINISHED,
    WORKOUT_STATUS_ERROR,
]

WORKOUT_STATUSES_CHOICES = [(s, s) for s in WORKOUT_STATUSES_LIST]
