WORKOUT_STATUS_PENDING = "pending"
WORKOUT_STATUS_PROCESSING = "processing"
WORKOUT_STATUS_FINISHED = "finished"
WORKOUT_STATUS_ERROR = "error"

WORKOUT_STATUSES_LIST = [
    WORKOUT_STATUS_PENDING,
    WORKOUT_STATUS_PROCESSING,
    WORKOUT_STATUS_FINISHED,
    WORKOUT_STATUS_ERROR,
]

WORKOUT_STATUSES_CHOICES = [(s, s) for s in WORKOUT_STATUSES_LIST]

# These are all from Garmin's fit SDK.
WORKOUT_GENERIC = "generic"
WORKOUT_RUNNING = "running"
WORKOUT_CYCLING = "cycling"
WORKOUT_TRANSITION = "transition"
WORKOUT_FITNESS_EQUIPMENT = "fitness_equipment"
WORKOUT_SWIMMING = "swimming"
WORKOUT_BASKETBALL = "basketball"
WORKOUT_SOCCER = "soccer"
WORKOUT_TENNIS = "tennis"
WORKOUT_AMERICAN_FOOTBALL = "american_football"
WORKOUT_TRAINING = "training"
WORKOUT_WALKING = "walking"
WORKOUT_CROSS_COUNTRY_SKIING = "cross_country_skiing"
WORKOUT_ALPINE_SKIING = "alpine_skiing"
WORKOUT_SNOWBOARDING = "snowboarding"
WORKOUT_ROWING = "rowing"
WORKOUT_MOUNTAINEERING = "mountaineering"
WORKOUT_HIKING = "hiking"
WORKOUT_MULTISPORT = "multisport"
WORKOUT_PADDLING = "paddling"
WORKOUT_FLYING = "flying"
WORKOUT_E_BIKING = "e_biking"
WORKOUT_MOTORCYCLING = "motorcycling"
WORKOUT_BOATING = "boating"
WORKOUT_DRIVING = "driving"
WORKOUT_GOLF = "golf"
WORKOUT_HANG_GLIDING = "hang_gliding"
WORKOUT_HORSEBACK_RIDING = "horseback_riding"
WORKOUT_HUNTING = "hunting"
WORKOUT_FISHING = "fishing"
WORKOUT_INLINE_SKATING = "inline_skating"
WORKOUT_ROCK_CLIMBING = "rock_climbing"
WORKOUT_SAILING = "sailing"
WORKOUT_ICE_SKATING = "ice_skating"
WORKOUT_SKY_DIVING = "sky_diving"
WORKOUT_SNOWSHOEING = "snowshoeing"
WORKOUT_SNOWMOBILING = "snowmobiling"
WORKOUT_STAND_UP_PADDLEBOARDING = "stand_up_paddleboarding"
WORKOUT_SURFING = "surfing"
WORKOUT_WAKEBOARDING = "wakeboarding"
WORKOUT_WATER_SKIING = "water_skiing"
WORKOUT_KAYAKING = "kayaking"
WORKOUT_RAFTING = "rafting"
WORKOUT_WINDSURFING = "windsurfing"
WORKOUT_KITESURFING = "kitesurfing"
WORKOUT_TACTICAL = "tactical"
WORKOUT_JUMPMASTER = "jumpmaster"
WORKOUT_BOXING = "boxing"
WORKOUT_FLOOR_CLIMBING = "floor_climbing"
WORKOUT_PICKLEBALL = "pickleball"
WORKOUT_ALL = "all"


# List of all workout types
WORKOUT_TYPES_LIST = [
    WORKOUT_GENERIC,
    WORKOUT_RUNNING,
    WORKOUT_CYCLING,
    WORKOUT_TRANSITION,
    WORKOUT_FITNESS_EQUIPMENT,
    WORKOUT_SWIMMING,
    WORKOUT_BASKETBALL,
    WORKOUT_SOCCER,
    WORKOUT_TENNIS,
    WORKOUT_AMERICAN_FOOTBALL,
    WORKOUT_TRAINING,
    WORKOUT_WALKING,
    WORKOUT_CROSS_COUNTRY_SKIING,
    WORKOUT_ALPINE_SKIING,
    WORKOUT_SNOWBOARDING,
    WORKOUT_ROWING,
    WORKOUT_MOUNTAINEERING,
    WORKOUT_HIKING,
    WORKOUT_MULTISPORT,
    WORKOUT_PADDLING,
    WORKOUT_FLYING,
    WORKOUT_E_BIKING,
    WORKOUT_MOTORCYCLING,
    WORKOUT_BOATING,
    WORKOUT_DRIVING,
    WORKOUT_GOLF,
    WORKOUT_HANG_GLIDING,
    WORKOUT_HORSEBACK_RIDING,
    WORKOUT_HUNTING,
    WORKOUT_FISHING,
    WORKOUT_INLINE_SKATING,
    WORKOUT_ROCK_CLIMBING,
    WORKOUT_SAILING,
    WORKOUT_ICE_SKATING,
    WORKOUT_SKY_DIVING,
    WORKOUT_SNOWSHOEING,
    WORKOUT_SNOWMOBILING,
    WORKOUT_STAND_UP_PADDLEBOARDING,
    WORKOUT_SURFING,
    WORKOUT_WAKEBOARDING,
    WORKOUT_WATER_SKIING,
    WORKOUT_KAYAKING,
    WORKOUT_RAFTING,
    WORKOUT_WINDSURFING,
    WORKOUT_KITESURFING,
    WORKOUT_TACTICAL,
    WORKOUT_JUMPMASTER,
    WORKOUT_BOXING,
    WORKOUT_FLOOR_CLIMBING,
    WORKOUT_PICKLEBALL,
    WORKOUT_ALL,
]

WORKOUT_TYPES_CHOICES = [(w, w) for w in WORKOUT_TYPES_LIST]
