# Generated by Django 5.2.1 on 2025-07-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_comment_created_on_comment_response_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
    ]
