# Generated by Django 5.2.1 on 2025-07-31 04:37

import django.db.models.deletion
from django.db import migrations, models

import activitypub.utils


class Migration(migrations.Migration):

    dependencies = [
        ("activitypub", "0001_initial"),
        ("workouts", "0003_workout_comment_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ap_id",
                    models.CharField(
                        default=activitypub.utils.generate_ulid, max_length=255
                    ),
                ),
                ("ap_uri", models.URLField(blank=True, max_length=1024, null=True)),
                ("local_uri", models.URLField(blank=True, max_length=1024, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitypub.actor",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.workout",
                    ),
                ),
            ],
        ),
    ]
