# Generated by Django 5.2.1 on 2025-07-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
