# Generated by Django 5.2.1 on 2025-07-31 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_workout_like_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="workouts.workout",
            ),
        ),
    ]
